controller_manager:
  ros__parameters:
    update_rate: 50

    # Joint state broadcaster (publishes all joint states)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Lift position controller
    lift_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - encoder_lift_joint

lift_controller:
  ros__parameters:
    joints:
      - encoder_lift_joint
